# This workflow will extract new translatable strings from files under /app and /tests into a base.pot file,
# and update the 'en' and 'he' base.po and base.mo files.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: update-translations

on: [push]

jobs:
  update-translations:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install prerequesits
        run: |
          python -m pip install --upgrade pip
          pip install pybabel

      - name: Create base.pot file
        run: pybabel extract --mapping-file=app/babel_mapping.ini app tests -o app/locales/base.pot -c i18n

      - name: Move to /app directory
        run: cd app

      - name: Update all language base.po files
        run: pybabel update -i locales/base.pot -d locales -D base

      - name: Update all .mo files
        run: pybabel compile -d locales -D base

      # https://github.com/stefanzweifel/git-auto-commit-action
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply automatic translateable string changes
